### ISSUE TITLE
Feat:  move requirements into prepare.yml

### ISSUE THREAD

**Issue by Cinux90** [while-true-do/ansible-role-app_ansible#1]
Currently requirements for the test are configured in `molecude/default/playbook.yml`
A better location will be `molecude/default/prepare.yml`
The content of the file should be:
```
---
- name: Prepare
  hosts: all
  roles:
    - role: while_true_do.rpo_epel
```
